// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/alpkeskin/rota"
        },
        "license": {
            "name": "LICENSE",
            "url": "https://github.com/alpkeskin/rota/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticate user and receive JWT token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/charts/response-time": {
            "get": {
                "description": "Get response time chart data for visualization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Response time chart",
                "parameters": [
                    {
                        "type": "string",
                        "default": "4h",
                        "description": "Time interval (e.g., 4h, 24h)",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chart data",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseTimeChartData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/charts/success-rate": {
            "get": {
                "description": "Get success rate chart data for visualization",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Success rate chart",
                "parameters": [
                    {
                        "type": "string",
                        "default": "4h",
                        "description": "Time interval (e.g., 4h, 24h)",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Chart data",
                        "schema": {
                            "$ref": "#/definitions/models.SuccessRateChartData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "description": "Get dashboard statistics including proxy and request metrics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard statistics",
                "responses": {
                    "200": {
                        "description": "Dashboard statistics",
                        "schema": {
                            "$ref": "#/definitions/models.DashboardStats"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/health": {
            "get": {
                "description": "Check database connection health",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Database health",
                "responses": {
                    "200": {
                        "description": "Database health information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/stats": {
            "get": {
                "description": "Get database connection pool statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Database statistics",
                "responses": {
                    "200": {
                        "description": "Database pool statistics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API server is running and healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Health status information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/logs": {
            "get": {
                "description": "Get paginated list of system logs with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "List logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by log level",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of logs",
                        "schema": {
                            "$ref": "#/definitions/models.LogListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logs/export": {
            "get": {
                "description": "Export system logs in various formats (txt, json)",
                "produces": [
                    "text/plain",
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Export logs",
                "parameters": [
                    {
                        "type": "string",
                        "default": "txt",
                        "description": "Export format (txt/json)",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by log level",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by source",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time (RFC3339)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time (RFC3339)",
                        "name": "end_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/metrics/system": {
            "get": {
                "description": "Get current system resource metrics (CPU, memory, disk, runtime) plus optional background-pipeline sections (health_check, global_health_check, geo, cleanup)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "System metrics",
                "responses": {
                    "200": {
                        "description": "System metrics",
                        "schema": {
                            "$ref": "#/definitions/handlers.SystemMetrics"
                        }
                    }
                }
            }
        },
        "/proxies": {
            "get": {
                "description": "Get paginated list of proxies with optional filters",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "List proxies",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Search term",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by protocol",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by country (ISO 3166-1 alpha-2)",
                        "name": "country_code",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort field",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order (asc/desc)",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of proxies",
                        "schema": {
                            "$ref": "#/definitions/models.ProxyListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new proxy server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Create proxy",
                "parameters": [
                    {
                        "description": "Proxy details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created proxy",
                        "schema": {
                            "$ref": "#/definitions/models.Proxy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/bulk": {
            "post": {
                "description": "Create multiple proxy servers at once",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Bulk create proxies",
                "parameters": [
                    {
                        "description": "List of proxies to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BulkCreateProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Creation results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/bulk-delete": {
            "post": {
                "description": "Delete multiple proxy servers at once",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Bulk delete proxies",
                "parameters": [
                    {
                        "description": "List of proxy IDs to delete",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BulkDeleteProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deletion results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/bulk-tags": {
            "post": {
                "description": "Add and/or remove tags on multiple proxies at once",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Bulk update proxy tags",
                "parameters": [
                    {
                        "description": "Proxy IDs and tags to add/remove",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BulkTagProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update results",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/cleanup/force": {
            "post": {
                "description": "Enqueue async batched deletion of all failed proxies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Force cleanup failed proxies",
                "responses": {
                    "200": {
                        "description": "Job already running, or nothing to clean",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "202": {
                        "description": "Job accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Health check queue is full",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/cleanup/run": {
            "post": {
                "description": "Synchronously delete dead proxies per cleanup settings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Run proxy cleanup now",
                "responses": {
                    "200": {
                        "description": "Cleanup result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/export": {
            "get": {
                "description": "Export proxy list in various formats (txt, json, csv)",
                "produces": [
                    "text/plain",
                    "application/json",
                    "text/csv"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Export proxies",
                "parameters": [
                    {
                        "type": "string",
                        "default": "txt",
                        "description": "Export format (txt/json/csv)",
                        "name": "format",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Exported file",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/reload": {
            "post": {
                "description": "Reload proxy pool from database",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Reload proxy pool",
                "responses": {
                    "200": {
                        "description": "Reload confirmation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/test/bulk": {
            "post": {
                "description": "Enqueue async health check for the given proxy IDs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Test selected proxies",
                "parameters": [
                    {
                        "description": "Proxy IDs to test",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.BulkTestProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Job accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Health check queue is full",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/test/global": {
            "post": {
                "description": "Enqueue async health check for orphan (pool-less) proxies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Test all orphan proxies",
                "responses": {
                    "202": {
                        "description": "Job accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Health check queue is full",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/test/idle": {
            "post": {
                "description": "Enqueue async health check for orphan proxies with status idle",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Test idle orphan proxies",
                "responses": {
                    "202": {
                        "description": "Job accepted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "429": {
                        "description": "Health check queue is full",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/test/{job_id}": {
            "get": {
                "description": "Get status of an async proxy test job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Proxy test job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Job ID",
                        "name": "job_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Job status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/{id}": {
            "put": {
                "description": "Update an existing proxy server",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Update proxy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Proxy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated proxy details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UpdateProxyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated proxy",
                        "schema": {
                            "$ref": "#/definitions/models.Proxy"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a proxy server by ID",
                "tags": [
                    "proxies"
                ],
                "summary": "Delete proxy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Proxy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/proxies/{id}/test": {
            "post": {
                "description": "Test a proxy server's connectivity and performance",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxies"
                ],
                "summary": "Test proxy",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Proxy ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Test results",
                        "schema": {
                            "$ref": "#/definitions/models.ProxyTestResult"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "description": "Get current system configuration",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get settings",
                "responses": {
                    "200": {
                        "description": "Current settings",
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update system configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update settings",
                "parameters": [
                    {
                        "description": "Updated settings",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Settings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Update confirmation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/settings/reset": {
            "post": {
                "description": "Reset configuration to default values",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Reset settings",
                "responses": {
                    "200": {
                        "description": "Reset confirmation",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Get detailed system status including proxy and request statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "System status",
                "responses": {
                    "200": {
                        "description": "Detailed status information",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "checkstats.CleanupMetrics": {
            "type": "object",
            "properties": {
                "force": {
                    "$ref": "#/definitions/checkstats.ForceCleanupSnapshot"
                },
                "log": {
                    "$ref": "#/definitions/checkstats.LogCleanupSnapshot"
                },
                "proxy": {
                    "$ref": "#/definitions/checkstats.ProxyCleanupSnapshot"
                }
            }
        },
        "checkstats.CleanupStatus": {
            "type": "string",
            "enum": [
                "idle",
                "ok",
                "error"
            ],
            "x-enum-varnames": [
                "CleanupStatusIdle",
                "CleanupStatusOK",
                "CleanupStatusError"
            ]
        },
        "checkstats.ForceCleanupSnapshot": {
            "type": "object",
            "properties": {
                "deleted_proxies": {
                    "type": "integer"
                },
                "last_duration_ms": {
                    "type": "integer"
                },
                "last_error": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "last_status": {
                    "$ref": "#/definitions/checkstats.CleanupStatus"
                }
            }
        },
        "checkstats.GlobalHealthCheckSnapshot": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "interval_minutes": {
                    "type": "integer"
                },
                "is_running": {
                    "type": "boolean"
                },
                "last_checked_proxies": {
                    "type": "integer"
                },
                "last_duration_ms": {
                    "type": "integer"
                },
                "last_error": {
                    "type": "string"
                },
                "last_finished_at": {
                    "type": "string"
                },
                "last_started_at": {
                    "type": "string"
                },
                "last_status": {
                    "$ref": "#/definitions/checkstats.GlobalHealthCheckStatus"
                },
                "next_run_at": {
                    "type": "string"
                }
            }
        },
        "checkstats.GlobalHealthCheckStatus": {
            "type": "string",
            "enum": [
                "idle",
                "ok",
                "error"
            ],
            "x-enum-varnames": [
                "GlobalHealthCheckStatusIdle",
                "GlobalHealthCheckStatusOK",
                "GlobalHealthCheckStatusError"
            ]
        },
        "checkstats.LogCleanupSnapshot": {
            "type": "object",
            "properties": {
                "compression_after_days": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "last_duration_ms": {
                    "type": "integer"
                },
                "last_error": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "last_status": {
                    "$ref": "#/definitions/checkstats.CleanupStatus"
                },
                "next_run_at": {
                    "type": "string"
                },
                "retention_days": {
                    "type": "integer"
                }
            }
        },
        "checkstats.ProxyCleanupSnapshot": {
            "type": "object",
            "properties": {
                "cleanup_interval_hours": {
                    "type": "integer"
                },
                "deleted_proxies": {
                    "type": "integer"
                },
                "enabled": {
                    "type": "boolean"
                },
                "last_duration_ms": {
                    "type": "integer"
                },
                "last_error": {
                    "type": "string"
                },
                "last_run_at": {
                    "type": "string"
                },
                "last_status": {
                    "$ref": "#/definitions/checkstats.CleanupStatus"
                },
                "max_failed_days": {
                    "type": "integer"
                },
                "min_success_rate": {
                    "type": "number"
                },
                "next_run_at": {
                    "type": "string"
                }
            }
        },
        "checkstats.Snapshot": {
            "type": "object",
            "properties": {
                "checks_last_minute": {
                    "type": "integer"
                },
                "processed_last_10m": {
                    "type": "integer"
                },
                "queue_pending": {
                    "type": "integer"
                },
                "success_percent_1m": {
                    "type": "number"
                }
            }
        },
        "handlers.CPUMetrics": {
            "type": "object",
            "properties": {
                "cores": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                }
            }
        },
        "handlers.DiskMetrics": {
            "type": "object",
            "properties": {
                "free": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "handlers.GeoMetrics": {
            "type": "object",
            "properties": {
                "batch_requests_last_minute": {
                    "type": "integer"
                },
                "batch_requests_limit": {
                    "type": "integer"
                },
                "ips_updated_last_10m": {
                    "type": "integer"
                },
                "provider": {
                    "type": "string"
                },
                "queue_pending": {
                    "type": "integer"
                },
                "queued_in_memory": {
                    "type": "integer"
                },
                "usage_percent_1m": {
                    "type": "number"
                }
            }
        },
        "handlers.MemoryMetrics": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "percentage": {
                    "type": "number"
                },
                "total": {
                    "type": "integer"
                },
                "used": {
                    "type": "integer"
                }
            }
        },
        "handlers.RuntimeMetrics": {
            "type": "object",
            "properties": {
                "gc_pause_count": {
                    "type": "integer"
                },
                "goroutines": {
                    "type": "integer"
                },
                "mem_alloc": {
                    "type": "integer"
                },
                "mem_sys": {
                    "type": "integer"
                },
                "threads": {
                    "type": "integer"
                }
            }
        },
        "handlers.SystemMetrics": {
            "type": "object",
            "properties": {
                "cleanup": {
                    "$ref": "#/definitions/checkstats.CleanupMetrics"
                },
                "cpu": {
                    "$ref": "#/definitions/handlers.CPUMetrics"
                },
                "disk": {
                    "$ref": "#/definitions/handlers.DiskMetrics"
                },
                "geo": {
                    "$ref": "#/definitions/handlers.GeoMetrics"
                },
                "global_health_check": {
                    "$ref": "#/definitions/checkstats.GlobalHealthCheckSnapshot"
                },
                "health_check": {
                    "$ref": "#/definitions/checkstats.Snapshot"
                },
                "memory": {
                    "$ref": "#/definitions/handlers.MemoryMetrics"
                },
                "runtime": {
                    "$ref": "#/definitions/handlers.RuntimeMetrics"
                }
            }
        },
        "models.AuthenticationSettings": {
            "type": "object",
            "properties": {
                "enabled": {
                    "description": "Enable authentication for proxy requests",
                    "type": "boolean"
                },
                "password": {
                    "description": "Password for proxy authentication (write-only)",
                    "type": "string"
                },
                "username": {
                    "description": "Username for proxy authentication",
                    "type": "string"
                }
            }
        },
        "models.BulkCreateProxyRequest": {
            "type": "object",
            "required": [
                "proxies"
            ],
            "properties": {
                "proxies": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/models.CreateProxyRequest"
                    }
                }
            }
        },
        "models.BulkDeleteProxyRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "models.BulkTagProxyRequest": {
            "type": "object",
            "required": [
                "ids"
            ],
            "properties": {
                "add": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "remove": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.BulkTestProxyRequest": {
            "type": "object",
            "required": [
                "proxy_ids"
            ],
            "properties": {
                "proxy_ids": {
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "workers": {
                    "type": "integer"
                }
            }
        },
        "models.ChartDataPoint": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "integer"
                }
            }
        },
        "models.CreateProxyRequest": {
            "type": "object",
            "required": [
                "address",
                "protocol"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string",
                    "enum": [
                        "http",
                        "https",
                        "socks4",
                        "socks4a",
                        "socks5"
                    ]
                },
                "source_id": {
                    "description": "set internally when importing from a source",
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.DashboardStats": {
            "type": "object",
            "properties": {
                "active_proxies": {
                    "type": "integer"
                },
                "avg_response_time": {
                    "type": "integer"
                },
                "avg_success_rate": {
                    "type": "number"
                },
                "request_growth": {
                    "type": "number"
                },
                "response_time_delta": {
                    "type": "integer"
                },
                "success_rate_growth": {
                    "type": "number"
                },
                "total_proxies": {
                    "type": "integer"
                },
                "total_requests": {
                    "type": "integer"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "models.GeoIPSettings": {
            "type": "object",
            "properties": {
                "auto_update": {
                    "description": "Enable automatic DB update on interval",
                    "type": "boolean"
                },
                "last_updated_at": {
                    "description": "Timestamp of last successful update",
                    "type": "string"
                },
                "maxmind_db_path": {
                    "description": "Path to local .mmdb file",
                    "type": "string"
                },
                "maxmind_license_key": {
                    "description": "MaxMind license key for auto-download",
                    "type": "string"
                },
                "maxmind_url": {
                    "description": "Custom download URL (optional)",
                    "type": "string"
                },
                "provider": {
                    "description": "\"ip-api\" or \"maxmind\"",
                    "type": "string"
                },
                "update_interval_hours": {
                    "description": "How often to update in hours (default 168 = 7 days)",
                    "type": "integer"
                }
            }
        },
        "models.GlobalHealthCheckSettings": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "interval_minutes": {
                    "type": "integer"
                }
            }
        },
        "models.HealthCheckSettings": {
            "type": "object",
            "properties": {
                "headers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "idle_ttl_minutes": {
                    "description": "IdleTTLMinutes is the same TTL filter for idle-orphan sweeps.",
                    "type": "integer"
                },
                "orphan_ttl_minutes": {
                    "description": "OrphanTTLMinutes excludes orphan proxies checked more recently than\nnow()-TTL from periodic orphan sweeps (0 disables the filter).",
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "strategy": {
                    "description": "Strategy selects how the health-check response body is validated after\nthe status-code check (see Strategy* constants). Empty normalizes to\nStrategyIP when settings are loaded, so the default is \"body must\ncontain an IP\" — catches proxies that answer the check URL with a valid\nstatus code but junk body (captive-portal HTML, login pages).",
                    "type": "string"
                },
                "strategy_value": {
                    "description": "StrategyValue is the value for the StrategyContains / StrategyRegex\nstrategies (substring / Go regex); unused by the other strategies.",
                    "type": "string"
                },
                "strict_tls": {
                    "description": "Enable real TLS certificate validation during health checks",
                    "type": "boolean"
                },
                "timeout": {
                    "type": "integer"
                },
                "url": {
                    "type": "string"
                },
                "workers": {
                    "type": "integer"
                }
            }
        },
        "models.Log": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.LogListResponse": {
            "type": "object",
            "properties": {
                "logs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Log"
                    }
                },
                "pagination": {
                    "$ref": "#/definitions/models.PaginationMeta"
                }
            }
        },
        "models.LogRetentionSettings": {
            "type": "object",
            "properties": {
                "cleanup_interval_hours": {
                    "description": "How often to run cleanup (1, 6, 12, 24)",
                    "type": "integer"
                },
                "compression_after_days": {
                    "description": "Compress logs older than X days (1, 3, 7, 14)",
                    "type": "integer"
                },
                "enabled": {
                    "description": "Enable automatic log cleanup",
                    "type": "boolean"
                },
                "retention_days": {
                    "description": "Days to keep logs (7, 15, 30, 60, 90)",
                    "type": "integer"
                }
            }
        },
        "models.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.UserInfoResponse"
                }
            }
        },
        "models.PaginationMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "models.Proxy": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avg_response_time": {
                    "type": "integer"
                },
                "city_name": {
                    "type": "string"
                },
                "country_code": {
                    "description": "GeoIP fields",
                    "type": "string"
                },
                "country_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "geo_updated_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isp": {
                    "type": "string"
                },
                "last_check": {
                    "type": "string"
                },
                "latitude": {
                    "type": "number"
                },
                "longitude": {
                    "type": "number"
                },
                "protocol": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "requests": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tags": {
                    "description": "Tags",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.ProxyCleanupSettings": {
            "type": "object",
            "properties": {
                "cleanup_interval_hours": {
                    "description": "How often to run cleanup",
                    "type": "integer"
                },
                "enabled": {
                    "description": "Enable automatic dead proxy cleanup",
                    "type": "boolean"
                },
                "max_failed_days": {
                    "description": "Remove proxies failed for more than N days",
                    "type": "integer"
                },
                "min_success_rate": {
                    "description": "Remove proxies with success rate below X% (0 = disabled)",
                    "type": "number"
                }
            }
        },
        "models.ProxyListResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/models.PaginationMeta"
                },
                "proxies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProxyWithStats"
                    }
                }
            }
        },
        "models.ProxyTestResult": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "response_time": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "tested_at": {
                    "type": "string"
                }
            }
        },
        "models.ProxyWithStats": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "avg_response_time": {
                    "type": "integer"
                },
                "city_name": {
                    "type": "string"
                },
                "country_code": {
                    "description": "GeoIP fields",
                    "type": "string"
                },
                "country_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isp": {
                    "type": "string"
                },
                "last_check": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "requests": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "success_rate": {
                    "type": "number"
                },
                "tags": {
                    "description": "Tags",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.RateLimitSettings": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "interval": {
                    "description": "in seconds",
                    "type": "integer"
                },
                "max_requests": {
                    "type": "integer"
                }
            }
        },
        "models.ResponseTimeChartData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ChartDataPoint"
                    }
                }
            }
        },
        "models.RotationSettings": {
            "type": "object",
            "properties": {
                "allowed_protocols": {
                    "description": "[\"http\", \"https\", \"socks4\", \"socks4a\", \"socks5\"], empty means all",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "fallback": {
                    "type": "boolean"
                },
                "fallback_max_retries": {
                    "type": "integer"
                },
                "follow_redirect": {
                    "type": "boolean"
                },
                "max_response_time": {
                    "description": "in milliseconds, 0 means no limit",
                    "type": "integer"
                },
                "method": {
                    "type": "string"
                },
                "min_success_rate": {
                    "description": "0-100, 0 means no minimum",
                    "type": "number"
                },
                "remove_unhealthy": {
                    "type": "boolean"
                },
                "retries": {
                    "type": "integer"
                },
                "time_based": {
                    "$ref": "#/definitions/models.TimeBasedSettings"
                },
                "timeout": {
                    "type": "integer"
                }
            }
        },
        "models.Settings": {
            "type": "object",
            "properties": {
                "authentication": {
                    "$ref": "#/definitions/models.AuthenticationSettings"
                },
                "geoip": {
                    "$ref": "#/definitions/models.GeoIPSettings"
                },
                "global_health_check": {
                    "$ref": "#/definitions/models.GlobalHealthCheckSettings"
                },
                "healthcheck": {
                    "$ref": "#/definitions/models.HealthCheckSettings"
                },
                "log_retention": {
                    "$ref": "#/definitions/models.LogRetentionSettings"
                },
                "proxy_cleanup": {
                    "$ref": "#/definitions/models.ProxyCleanupSettings"
                },
                "rate_limit": {
                    "$ref": "#/definitions/models.RateLimitSettings"
                },
                "rotation": {
                    "$ref": "#/definitions/models.RotationSettings"
                }
            }
        },
        "models.SuccessRateChartData": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SuccessRateDataPoint"
                    }
                }
            }
        },
        "models.SuccessRateDataPoint": {
            "type": "object",
            "properties": {
                "failure": {
                    "type": "integer"
                },
                "success": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "models.TimeBasedSettings": {
            "type": "object",
            "properties": {
                "interval": {
                    "description": "in seconds",
                    "type": "integer"
                }
            }
        },
        "models.UpdateProxyRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string",
                    "enum": [
                        "http",
                        "https",
                        "socks4",
                        "socks4a",
                        "socks5"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserInfoResponse": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Rota Proxy API",
	Description:      "A high-performance proxy rotation server with health monitoring and intelligent routing\nProvides comprehensive API for managing proxy servers, monitoring their health,\nand configuring rotation strategies.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
